const genresKR: string[] = [
  "기묘한 서부극",
  "디젤펑크",
  "타임 트래블",
  "포스트 아포칼립스 생존물",
  "러브크래프트 호러",
  "바이오 펑크",
  "사이버 펑크",
  "클락 펑크",
  "느와르",
  "도시 괴담",
  "다크 유머",
  "크립토동물학",
  "외계인 침공물",
  "초자연 수사극",
  "법학 스릴러",
  "의학 스릴러",
  "테크노 스릴러",
  "안티히어로",
  "아서왕 전설",
  "노르드 신화",
  "그리스 신화",
  "이집트 신화",
  "아즈텍 신화",
  "타임루프",
  "스페이스 오페라",
  "하드 SF",
  "소프트 SF",
  "사이보그물",
  "뮤턴트물",
  "유전 공학물",
  "마인드컨트롤",
  "식민시대",
  "고대",
  "중세",
  "르네상스",
  "빅토리안",
  "계몽 시대",
  "세계대전",
  "냉전",
  "산업혁명",
  "궁정음모",
  "정치풍자",
  "은하제국",
  "잃어버린 세계",
  "신화적 생물",
  "가상세계",
  "엘드리치 공포물",
  "고딕 로맨스",
  "삼각관계",
  "금지된 사랑",
  "환생 로맨스",
  "기억상실",
  "대체현실",
  "미로",
  "평행세계",
  "선택받은 자",
  "어두운 예언",
  "비밀 결사",
  "잃어버린 보물",
  "고대 유물",
  "저주받은 물건",
  "유물 사냥꾼",
  "기사물",
  "괴물 사냥꾼",
  "초자연 탐정",
  "오컬트 탐정",
  "바다 괴물",
  "유령이 나오는 물건",
  "미해결 미스터리",
  "초자연 생물",
  "역사 판타지",
];

const genresEN: string[] = [
  "Weird West",
  "Dieselpunk",
  "Time Travel Adventure",
  "Post-Apocalyptic Survival",
  "Lovecraftian Horror",
  "Biopunk",
  "Cyberpunk",
  "Clockpunk",
  "Noir",
  "Urban Horror",
  "Dark Humor",
  "Cryptozoology",
  "Alien Invasion",
  "Paranormal Investigation",
  "Legal Thriller",
  "Medical Thriller",
  "Techno-Thriller",
  "Antihero",
  "Arthurian Legend",
  "Nordic Mythology",
  "Greek Mythology",
  "Egyptian Mythology",
  "Aztec Mythology",
  "Time Loop",
  "Space Opera",
  "Hard Science Fiction",
  "Soft Science Fiction",
  "Cyborg",
  "Mutant",
  "Genetic Engineering",
  "Mind Control",
  "Colonial",
  "Ancient World",
  "Medieval",
  "Renaissance",
  "Victorian",
  "Enlightenment",
  "World War",
  "Cold War",
  "Industrial Revolution",
  "Court Intrigue",
  "Political Satire",
  "Intergalactic Empire",
  "Lost World",
  "Mythical Creatures",
  "Virtual World",
  "Eldritch Horror",
  "Gothic Romance",
  "Love Triangle",
  "Forbidden Love",
  "Reincarnation Romance",
  "Amnesia",
  "Alternate Reality",
  "Maze",
  "Parallel World",
  "Chosen One",
  "Dark Prophecy",
  "Secret Society",
  "Lost Treasure",
  "Ancient Artifact",
  "Cursed Object",
  "Relic Hunter",
  "Knight",
  "Monster Hunter",
  "Supernatural Detective",
  "Occult Detective",
  "Sea Monsters",
  "Haunted Objects",
  "Unsolved Mystery",
  "Supernatural Creatures",
  "Historical Fantasy",
];

const fetchGenres = async (language: string = 'en'): Promise<string[]> => {
  if (language === 'kr') {
    return genresKR;
  }
  return genresEN;
};

export default fetchGenres;
